// <auto-generated />
using System;
using CrossSolar.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CrossSolar.Migrations
{
    [DbContext(typeof(CrossSolarDbContext))]
    [Migration("20180911145718_changeDataTypekiloWatt-ONHourElectricityModel")]
    partial class changeDataTypekiloWattONHourElectricityModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rc1-32029")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CrossSolar.Domain.OneHourElectricity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateTime");

                    b.Property<double>("KiloWatt");

                    b.Property<string>("PanelId");

                    b.HasKey("Id");

                    b.ToTable("OneHourElectricitys");
                });

            modelBuilder.Entity("CrossSolar.Domain.Panel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Brand");

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<string>("Serial")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Panels");
                });
#pragma warning restore 612, 618
        }
    }
}
